services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:v1
  backend:
    build:
      context: ./backend
    image: backend:
  frontend:
    build:
      context: ./react-dp
    image: frontend:v1