services:
  mysql:
    image: mysql:v1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CrudApp@1
    restart: on-failure
    networks:
      - compose-expense
  backend:
    image: backend:v1
    container_name: backend
    environment:
      - DB_HOST=mysql
      - DB_USER=crud
      - DB_PASSWORD=CrudApp@1
      - DB_NAME=crud_app
    restart: on-failure
    networks:
      - compose-expense
  frontend:
    image: backend:v1
    container_name: backend
    volumes:
      - ${PWD}/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - compose-expense
networks:
 compose-expense:
   driver: bridge