services:
  debug:
    image: alpine
    container_name: debug
    command: sh
    tty: true
    stdin_open: true
    networks:
      - compose-expense

  mysql:
    image: mysql:8
    container_name: mysql:v1
    environment:
      - MYSQL_ROOT_PASSWORD=CrudApp@1
      - MYSQL_DATABASE=crud_app
      - MYSQL_USER=crud
      - MYSQL_PASSWORD=CrudApp@1
    restart: always
    networks:
      - compose-expense

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - compose-expense

  backend:
    image: backend:v1
    container_name: backend
    environment:
      - DB_HOST=mysql
      - DB_USER=crud
      - DB_PASSWORD=CrudApp@1
      - DB_NAME=crud_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - compose-expense

  frontend:
    image: frontend:v1
    container_name: frontend
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - compose-expense

networks:
  compose-expense:
    driver: bridge
